version: "3"
services:
  backend:
    build:
      context: ./BACK
    ports:
      - "4000:4000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./FRONT
    ports:
      - "8000:8000"